name: commonloginpackage
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  pinput: ^2.2.23
  grouped_list: ^5.1.2
  provider: ^6.0.2
  http: ^0.13.4
  bot_toast: ^4.0.1
  auto_size_text: ^3.0.0
  logger: ^1.1.0
  url_launcher: ^6.0.20
  syncfusion_flutter_calendar: ^20.4.49
  package_info_plus: ^3.0.3
  crypto: ^3.0.2
  color: ^3.0.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  path_provider: ^2.0.9
  intl: ^0.17.0
  xml: ^6.2.2  
  brotli: ^0.5.0  
  convert: ^3.0.1 
  drift: ^2.5.0 
  sqlite3_flutter_libs: ^0.5.12
  path: ^1.8.2
  pointycastle: ^3.5.1
  device_info_plus: ^8.1.0
  firebase_messaging: ^14.2.1
  shared_preferences: ^2.0.13 
  get_storage: ^2.0.3
  drift_dev: ^2.5.2
  build_runner: ^2.3.3
  dartz: ^0.10.1
  scrollable_positioned_list: ^0.3.5   
  scroll_to_index: ^3.0.1
  syncfusion_flutter_charts: ^20.1.52
  image_picker: ^0.8.5
  get_it: ^7.2.0
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  flutter_local_notifications: ^13.0.0
  # google_sign_in: ^5.3.3
  flutter_udid: ^2.0.0
  connectivity_plus: ^3.0.3
  loading_indicator: ^3.1.0
  async: ^2.8.2
  account_picker:
      git: https://github.com/tolotrasamuel/account_picker
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1
  #package importing from our git repo
  # text_field:
  #   git: http://172.16.11.6:8080/ARMS_NG/ATSM/_git/ATSMMobileFlutterPackages
#    git: http://172.16.11.17:8080/tfs/ASMS/ASMSAOM/_git/Flutter_Packages
  dropdown_button2: ^1.8.5
  change_app_package_name: ^1.1.0
  device_calendar: ^4.2.0
  flutter_native_timezone: ^2.0.0
  file_picker: ^5.2.5
  webview_flutter: ^4.0.2
  flutter_spinkit: ^5.1.0
  dotted_decoration: ^2.0.0
  data_table_2: ^2.3.8
  flutter_svg: ^2.0.0+1
  visibility_detector: ^0.3.3
  android_id: ^0.1.3+1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/images/menu icon/
    - assets/images/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
